# Base image
FROM python:3.10-slim

# Working directory
WORKDIR /app

# Install dependencies
COPY requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

# Copy Streamlit UI code
COPY ui/ ui/

# Expose Streamlit port
EXPOSE 8501
EXPOSE 30007

# Start Streamlit app
# CMD ["streamlit", "run", "ui/app.py", "--server.address", "0.0.0.0"]
# CMD ["streamlit", "run", "ui/app.py", "--server.port", "8501"]
CMD ["streamlit", "run", "ui/app.py", "--server.port", "8501",  "--server.address", "0.0.0.0"]
